[package]

name = "collabfict"
version = "0.0.1"
authors = [ "Ash Wilson <smashwilson@gmail.com>" ]

[[bin]]

name = "collabfict"

[dependencies]
log = "0.2.1"
env_logger = "0.2.1"
iron = "0.1.5"
router = "0.0.8"
